name: flutter_ai_chat
description: "Flutter AI Chat Sample"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  firebase_ai: ^3.6.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_ui_auth: ^3.0.1
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^0.10.0
  flutter_markdown_plus: ^1.0.5
  future_builder_ex: ^5.0.0
  gap: ^3.0.1
  go_router: ^17.0.0
  shared_preferences: ^2.3.2
  split_view: ^3.2.1
  uuid: ^4.5.1

dev_dependencies:
  all_lint_rules_community: ^0.0.43

flutter:
  uses-material-design: true
